server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nosql?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50        # 增加连接池大小
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  redis:
    cluster:
      nodes:
        - 192.168.231.4:7000
        - 192.168.231.4:7001
        - 192.168.231.5:7002
        - 192.168.231.5:7003
        - 192.168.231.6:7004
        - 192.168.231.6:7005
      max-redirects: 3
    password: 
    timeout: 5000ms  # 增加超时时间
    lettuce:
      pool:
        max-active: 200   # 大幅增加连接池大小
        max-idle: 50
        min-idle: 10
        max-wait: 3000ms  # 设置合理等待时间
      cluster:
        refresh:
          adaptive: true    # 启用自适应刷新
          period: 30s       # 定期刷新集群拓扑
  
  rabbitmq:
    spring:
      rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        virtual-host: /
        listener:
          simple:
            concurrency: 10           # 增加消费者并发数
            max-concurrency: 20
            prefetch: 50             # 预取消息数量
            acknowledge-mode: auto
        template:
          mandatory: true
          confirm-callback: true
        publisher-confirm-type: correlated

logging:
  level:
    com.example.ecommerceredisdemo: DEBUG
    org.springframework.data.redis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"